### ISSUE TITLE
这个能通过字段找吗？比如指定一个filedname。Find方法只能找第一个字段吗？

### ISSUE THREAD

**Issue by jevonsflash** [Blueve/ORM-ObjectRedisMapping#64]

**Comment by Blueve** [comment]
就像关系型数据库，每个entity都会有一个唯一主键，所以Find方法只可以去找每个entity的主键。选取哪个field做主键可以自己决定，例如：https://github.com/Blueve/ORM-ObjectRedisMapping/blob/master/ObjectRedisMappingUnitTests/Model/PlainEntity.cs

需要一次检索多个条目并不适合使用redis，所以这里不予考虑。

如果需要以entity的其他field做查询条件，之前考虑过（比如增加一个额外的Index attribute，让engine为所有标记了Index field自动创建索引），但是现在并未实现……_(:3」∠)

**Comment by jevonsflash** [comment]
哦，开始没仔细看Demo，原来是要指定一个Entity字段，原来以为可以Save一个集合，然后通过指定一个字段去Where查询。
另外想问个问题，为啥字段要加virtual呢？

**Comment by Blueve** [comment]
virutal的目的是为了给实体类创建动态代理类，从而把`内存中get`悄无声息地变换为`从redis中get`

**Comment by jevonsflash** [comment]
不是很明白，这个是用于性能提升吗，不加这个virtual也能用反射吧。
从使用场景来说实体类也大多是模板生成了，如果要用这套都要改成virtual也不方便。
我还真试了一下不带virtual的，发现写入和读取都成功了，使用上还算正常。除了个小问题：如果对象包含DateTime类型的字段用Save就直接死循环写XXXToDayToDayToDay......，应该是在生成的时候把DateTime标记成ObjectMetadata的类型了，DateTime这个属性可以循环点出ToDay这个属性的， 导致不断的扩展字段堆栈，加了virtual就给拦截不会循环。
所以我有点不明白是为了性能加virtual还是为了实现功能才加的

**Comment by Blueve** [comment]
实体类是使用者自己定义的，加virtual是为了能够动态地改变实体类getter/setter的行为，这是功能上的需求而不是出于性能的考虑。

假如你创建了一个实体类`EntityA`，你从db context中Find到的对象也会是`EntityA`这个类型，你用getter获取属性的时候将会从redis里去读，你用setter更新属性的时候会直接写入redis

对应的设计参考了EF的relationships properties (https://docs.microsoft.com/en-us/ef/ef6/fundamentals/relationships)

你没用virtual也成功的原因可能是CLR背后总是使用callvirt来调用instance object的getter/setter，所以即便你没有显式指定virutal，他最终的行为也会和virutal一样。

DateTime的问题其实纯属目前并不支持这种内置的struct... 之前考虑的是提供一个额外的attribute（比如CompactAttribute）用于标记这类property，最后在实际执行的时候会使用指定的序列化器将其getter/setter转换为反序列化/序列化。

**Comment by jevonsflash** [comment]
哦，原来是这样。我测试了一下，把DateTime类型标记成TypeMeta，然后写了个DateTimeSetter和Getter， 在不加virtual的情况下也会调用到他，这样DateTime数据也不会出错。
另外问下，为啥不用Hash方式存储，而是用键值对存呢。Hash更适合对象存储吧。

**Comment by Blueve** [comment]
你指的是哪里用了键值对存储呢？如果说`TypeMetadata`的话，是希望能够cache住已经创建好的metadata，再次访问的时候就可以免去反射的开销
